### ISSUE TITLE
Parse date in JSON into ISO format

### ISSUE THREAD

**Issue by Deborah-Digges** [karthikb351/OpenCAD#2]
Right now, the date field in the index is a string like this:
`"date":"Tuesday, the 29th April, 1947"`
We need to parse it into a format that would make date based searching faster; YYYY-MM-DD, maybe.
For now, assuming the format to be`<DAY>, the <DATE><SUFFIX> <MONTH>, <YEAR>`

**Comment by kishore-narendran** [comment]
041ad04f6fc969915cdb4374883a149d7539fa9f this should do the trick.
